### ISSUE TITLE
Cant run $user->billing()->withCardToken() - billing() is NULL=

### ISSUE THREAD

**Issue by canfiax** [mmanos/laravel-billing#11]
I can't run:

     $user->billing()->withCardToken($data['stripeToken'])->create();

as per documentation. I get error: Call to a member function customer() on null

![image](https://cloud.githubusercontent.com/assets/3786627/6512517/d7f231a4-c374-11e4-8dc2-cf584e89287f.png)

Why?

Running laravel 5. See my fork.

**Comment by anilngbm** [comment]
Issue Solved. Please see my fork.

**Comment by AndreasHeiberg** [comment]
+1 Please merge this does indeed fix the issue!

**Comment by mmanos** [comment]
Thanks guys for the help. I've merged in the pull request.

And yes, unit tests should be in here, so any help with that would be appreciated. I never expected so many others to use this package.
