### ISSUE TITLE
Store creditcards -- where?

### ISSUE THREAD

**Issue by simplenotezy** [mmanos/laravel-billing#12]
Doing:

```
$user->billing()->withCardToken($data['stripeToken'])->create();
```

or

```
$user->creditcards()->create($data['stripeToken']);
```

Where is the creditcards stored? In Stripe? I've configured to use Stripe, but I don't find anything in the admin panel.

**Comment by dmyers** [comment]
In order to reduce liability and PCI compliance, card data is sent to Stripe using their JS SDK and this package only gets a token which is used to charge and subscribe to plans.

Cards are currently stored attached to the model you setup from the readme which might be user under a cards property.
