### ISSUE TITLE
Detect and fire events around card expirations

### ISSUE THREAD

**Issue by dmyers** [mmanos/laravel-billing#4]
It would be very helpful to detect both cards expiring and expired and fire `customerCardExpiring` and  `customerCardExpired` events respectively in order to send emails to customers to proactively keep recurring payments flowing without disruption. Some event data such as Carbon objects of `expiring_at` and `expired_at` might be nice as arguments to create emails around when communicating with customers.

Since the cards are stored with their expirations, the way this could be solved is by creating a new `billing:checkcardexpirations` artisan command which detects and fires the events and one could simply add a cron to run the command monthly.

**Comment by mmanos** [comment]
It's a good suggestion. Just need to figure out how to loop through all of the customers and their cards in an efficient way. Could definitely be a problem if you have thousands or millions of customer records...

**Comment by dmyers** [comment]
It's pretty standard practice in the ecommerce industry which decreases churn.

**Comment by cdolan92** [comment]
Sorry if this is not the proper medium for this, but I saw this blog post the other day from Stripe about ‘smarter’ expiring cards and was pretty impressed by it. Perhaps it may be something to consider when dealing with your own ‘upcoming expirations': 

https://stripe.com/blog/smarter-saved-cards <https://stripe.com/blog/smarter-saved-cards>

**Comment by dmyers** [comment]
This is now built into Stripe Billing as a setting.
