### ISSUE TITLE
how to install for L5?

### ISSUE THREAD

**Issue by autocar** [mmanos/laravel-billing#9]
how to install for L5?

**Comment by canfiax** [comment]
+1 what about support for L5?

**Comment by yabdab** [comment]
+1

**Comment by sdeering** [comment]
+1

**Comment by dennisoderwald** [comment]
+1

**Comment by simonstamm** [comment]
+1

**Comment by rogeryu23** [comment]
any update?

**Comment by valenet** [comment]
Please see my fork. I am using this for Laravel 5. (verified stripe only)

**Comment by bart** [comment]
An update to L5 would be great!

**Comment by bryceadams** [comment]
@bart you may use my fork - https://github.com/bryceadams/laravel-billing

**Comment by bart** [comment]
I could but you didn't test braintree so using the original package would be better. Last but not least including braintree should be easy and possible without using any third party package than braintree itself.

**Comment by natsu90** [comment]
+1

**Comment by dmyers** [comment]
We recommend the official Laravel Cashier package for Laravel 5 users.
